<?php

use Illuminate\Database\Seeder;

class PhoneDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('phone_detail')->insert([
            //samsung note 20
            [
                'id' => '1',
                'phone_id' => '1',
                'color' => 'Mystic Green',
                'memory' => 8,
                'storage' => 256,
                'stock' => 50,
                'price' => 14499000,
            ],
            // [
            //     'id' => '2',
            //     'phone_id' => '1',
            //     'color' => 'Mystic Gray',
            //     'memory' => 8,
            //     'storage' => 256,
            //     'stock' => 100,
            //     'price' => 14499000,
            // ],
            // [
            //     'id' => '3',
            //     'phone_id' => '1',
            //     'color' => 'Mystic Bronze',
            //     'memory' => 8,
            //     'storage' => 256,
            //     'stock' => 25,
            //     'price' => 14499000,
            // ],

            //samsung s20 plus
            [
                'id' => '2',
                'phone_id' => '2',
                'color' => 'Cosmic Gray',
                'memory' => 8,
                'storage' => 128,
                'stock' => 50,
                'price' => 16999000,
            ],
            // [
            //     'id' => '5',
            //     'phone_id' => '2',
            //     'color' => 'Cloud Blue',
            //     'memory' => 8,
            //     'storage' => 128,
            //     'stock' => 25,
            //     'price' => 16999000,
            // ],
            // [
            //     'id' => '6',
            //     'phone_id' => '2',
            //     'color' => 'Cosmic Black',
            //     'memory' => 8,
            //     'storage' => 128,
            //     'stock' => 50,
            //     'price' => 16999000,
            // ],

            //samsung galaxy A51
            // [
            //     'id' => '7',
            //     'phone_id' => '3',
            //     'color' => 'Prism Crush Blue',
            //     'memory' => 6,
            //     'storage' => 128,
            //     'stock' => 120,
            //     'price' => 4399000,
            // ],
            [
                'id' => '3',
                'phone_id' => '3',
                'color' => 'Prism Crush Black',
                'memory' => 8,
                'storage' => 128,
                'stock' => 120,
                'price' => 4699000,
            ],
            // [
            //     'id' => '9',
            //     'phone_id' => '3',
            //     'color' => 'Haze Crush Silver',
            //     'memory' => 6,
            //     'storage' => 128,
            //     'stock' => 120,
            //     'price' => 4399000,
            // ],
            // [
            //     'id' => '10',
            //     'phone_id' => '3',
            //     'color' => 'Prism Crush White',
            //     'memory' => 8,
            //     'storage' => 128,
            //     'stock' => 100,
            //     'price' => 4699000,
            // ],

            //samsung galaxy A50S
            [
                'id' => '4',
                'phone_id' => '4',
                'color' => 'Prism Crush Purple',
                'memory' => 4,
                'storage' => 64,
                'stock' => 20,
                'price' => 3199000,
            ],
            // [
            //     'id' => '11',
            //     'phone_id' => '4',
            //     'color' => 'Prism Crush Green',
            //     'memory' => 4,
            //     'storage' => 64,
            //     'stock' => 5,
            //     'price' => 3199000,
            // ],
            // [
            //     'id' => '12',
            //     'phone_id' => '4',
            //     'color' => 'Prism Crush Black',
            //     'memory' => 6,
            //     'storage' => 128,
            //     'stock' => 20,
            //     'price' => 3900000,
            // ],

            //samsung galaxy A01
            // [
            //     'id' => '13',
            //     'phone_id' => '5',
            //     'color' => 'Blue',
            //     'memory' => 2,
            //     'storage' => 16,
            //     'stock' => 100,
            //     'price' => 1249000,
            // ],
            // [
            //     'id' => '14',
            //     'phone_id' => '5',
            //     'color' => 'Black',
            //     'memory' => 2,
            //     'storage' => 16,
            //     'stock' => 100,
            //     'price' => 1249000,
            // ],
            [
                'id' => '5',
                'phone_id' => '5',
                'color' => 'Red',
                'memory' => 2,
                'storage' => 16,
                'stock' => 100,
                'price' => 1249000,
            ],


            //Apple
            [
                'id' => '6',
                'phone_id' => '6',
                'color' => 'Gold',
                'memory' => 2,
                'storage' => 64,
                'stock' => 100,
                'price' => 7499000,
            ],
            [
                'id' => '7',
                'phone_id' => '7',
                'color' => 'Gold',
                'memory' => 2,
                'storage' => 128,
                'stock' => 100,
                'price' => 10499000,
            ],
            [
                'id' => '8',
                'phone_id' => '8',
                'color' => '(PRODUCT) RED',
                'memory' => 2,
                'storage' => 64,
                'stock' => 100,
                'price' => 6950000,
            ],
            [
                'id' => '9',
                'phone_id' => '9',
                'color' => '(PRODUCT) RED',
                'memory' => 2,
                'storage' => 64,
                'stock' => 100,
                'price' => 10000000,
            ],
            [
                'id' => '10',
                'phone_id' => '10',
                'color' => 'Yellow',
                'memory' => 2,
                'storage' => 128,
                'stock' => 100,
                'price' => 11200000,
            ],
            // [
            //     'id' => '17',
            //     'phone_id' => '6',
            //     'color' => 'Silver',
            //     'memory' => 2,
            //     'storage' => 128,
            //     'stock' => 100,
            //     'price' => 9999000,
            // ],
            // [
            //     'id' => '18',
            //     'phone_id' => '6',
            //     'color' => 'Space Grey',
            //     'memory' => 2,
            //     'storage' => 256,
            //     'stock' => 100,
            //     'price' => 8499000,
            // ],
            // [
            //     'id' => '19',
            //     'phone_id' => '6',
            //     'color' => '(PRODUCT) RED',
            //     'memory' => 2,
            //     'storage' => 64,
            //     'stock' => 100,
            //     'price' => 7499000,
            // ],

            // Oppo
            [
                'id' => '11',
                'phone_id' => '11',
                'color' => 'Silver',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 3200000,
            ],
            [
                // 'id' => '19',
                'id' => '12',
                'phone_id' => '12',
                'color' => 'Black',
                'memory' => 8,
                'storage' => 256,
                'stock' => 100,
                'price' => 6200000,
            ],
            [
                // 'id' => '19',
                'id' => '13',
                'phone_id' => '13',
                'color' => 'Orange',
                'memory' => 12,
                'storage' => 512,
                'stock' => 100,
                'price' => 17999000,
            ],
            [
                // 'id' => '19',
                'id' => '14',
                'phone_id' => '14',
                'color' => 'Metallic Black',
                'memory' => 12,
                'storage' => 256,
                'stock' => 100,
                'price' => 10999000,
            ],
            [
                // 'id' => '19',
                'id' => '15',
                'phone_id' => '15',
                'color' => 'Sky Blue',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 3400000,
            ],

            //realme
            [
                // 'id' => '19',
                'id' => '16',
                'phone_id' => '16',
                'color' => 'Blue/Turqoise',
                'memory' => 6,
                'storage' => 256,
                'stock' => 100,
                'price' => 2519000,
            ],
            [
                // 'id' => '19',
                'id' => '17',
                'phone_id' => '17',
                'color' => 'Metallic Silver',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 4049000,
            ],
            [
                // 'id' => '19',
                'id' => '18',
                'phone_id' => '18',
                'color' => 'Metallic Blue',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 3198000,
            ],
            [
                // 'id' => '19',
                'id' => '19',
                'phone_id' => '19',
                'color' => 'Metallic Blue',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 3799000,
            ],
            [
                // 'id' => '19',
                'id' => '20',
                'phone_id' => '20',
                'color' => 'Red',
                'memory' => 12,
                'storage' => 256,
                'stock' => 100,
                'price' => 11999000,
            ],

            // Vivo
            [
                // 'id' => '19',
                'id' => '21',
                'phone_id' => '21',
                'color' => 'Blue',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 1999000,
            ],
            [
                // 'id' => '19',
                'id' => '22',
                'phone_id' => '22',
                'color' => 'Purple',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 4399000,
            ],
            [
                // 'id' => '19',
                'id' => '23',
                'phone_id' => '23',
                'color' => 'Green',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 1599000,
            ],
            [
                // 'id' => '19',
                'id' => '24',
                'phone_id' => '24',
                'color' => 'Ocean Blue',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 5700000,
            ],
            [
                // 'id' => '19',
                'id' => '25',
                'phone_id' => '25',
                'color' => 'Metallic Grey',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 8999000,
            ],

            // Huawei
            [
                // 'id' => '19',
                'id' => '26',
                'phone_id' => '26',
                'color' => 'Metallic Blue',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 8849000,
            ],
            [
                // 'id' => '19',
                'id' => '27',
                'phone_id' => '27',
                'color' => 'Black',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 14499000,
            ],
            [
                // 'id' => '19',
                'id' => '28',
                'phone_id' => '28',
                'color' => 'Purple',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 12500000,
            ],
            [
                // 'id' => '19',
                'id' => '29',
                'phone_id' => '29',
                'color' => 'MEtalic Purple',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 8700000,
            ],
            [
                // 'id' => '19',
                'id' => '30',
                'phone_id' => '30',
                'color' => 'White',
                'memory' => 8,
                'storage' => 128,
                'stock' => 100,
                'price' => 4250000,
            ],
        ]);
    }
}
